name: pipeline
on: [push]

jobs:
    unit_tests_php72:
        name: Unit tests PHP 7.2
        needs: install_dev_dependencies
        runs-on: ubuntu-latest
        steps:
            -   uses: docker://php:7.2
            -   uses: actions/checkout@v1
            -   run: composer install --no-ansi --no-progress
            -   run: ./vendor/bin/phpunit
    unit_tests_php73:
        name: Unit tests PHP 7.3
        runs-on: ubuntu-latest
        steps:
            -   uses: docker://php:7.3
            -   uses: actions/checkout@v1
            -   run: composer install --no-ansi --no-progress
            -   run: ./vendor/bin/phpunit
    unit_tests_php74:
        name: Unit tests PHP 7.4
        runs-on: ubuntu-latest
        steps:
            -   uses: docker://php:7.4
            -   uses: actions/checkout@v1
            -   run: composer install --no-ansi --no-progress
            -   run: ./vendor/bin/phpunit
    codesniffer_php72:
        name: Code style violations
        runs-on: ubuntu-latest
        steps:
            -   uses: docker://php:7.2
            -   uses: actions/checkout@v1
            -   run: composer install --no-ansi --no-progress
            -   run: ./vendor/bin/phpcs --standard=PSR12 src